language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
env:
  - MOZ_HEADLESS=1
cache:
  directories:
    - node_modules
    - bower_components
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm install
  - npm install -g bower
  - bower install
  - gulp copy
  - sh -e /etc/init.d/xvfb start
  - sleep 3
<% if (sauceLabs === true) { %>
script:
  - npm run remote-test
<% } %>
