language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
    - bower_components
addons:
  firefox: latest<% if (sauceLabs === true) { %>
  <%}%>
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- gulp copy
script:
 - xvfb-run wct<% if (sauceLabs === true) { %>
 - 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then polymer lint; fi'
 - 'if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run remote-test; fi'
<% } %>
