language: node_js
node_js: stable
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
    - bower_components
addons:
  firefox: latest
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- gulp copy
<% if (sauceLabs === true) { %>
script:
- 'if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then polymer lint; fi'
- 'if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm run remote-test; fi'
<% } %>
